import { StyleSheet } from 'react-native';

export const createStyles = (width: number, height: number) => {
  const isTablet = width >= 768;
  
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#020617',
    },
    background: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: -2,
    },
    spotlightOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(15, 23, 42, 0.45)',
      zIndex: -1,
    },
    radarOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: -1,
    },
    radarLine: {
      width: '100%',
      height: 2,
      backgroundColor: 'rgba(16, 185, 129, 0.15)',
      position: 'absolute',
      top: 100,
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 20,
    },
    card: {
      width: isTablet ? '75%' : '92%',
      maxWidth: 420,
      backgroundColor: 'rgba(15, 23, 42, 0.85)',
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.4)',
      borderTopWidth: 4,
      borderTopColor: '#fbbf24',
      padding: isTablet ? 32 : 24,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 6,
    },
    logoContainer: {
      alignItems: 'center',
      marginBottom: 20,
    },
    logoEmblemContainer: {
      width: 85,
      height: 85,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    logoLayerAbsolute: {
      position: 'absolute',
      width: 85,
      height: 85,
    },
    logoTitle: {
      fontSize: isTablet ? 34 : 28,
      fontWeight: 'bold',
      color: '#ffffff',
      letterSpacing: 3,
      textShadowColor: 'rgba(251, 191, 36, 0.6)',
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 10,
    },
    logoBorder: {
      height: 1,
      backgroundColor: 'rgba(251, 191, 36, 0.25)',
      width: 140,
      marginVertical: 6,
    },
    logoSubtitle: {
      fontSize: 9,
      color: '#fbbf24',
      fontWeight: '900',
      letterSpacing: 1.5,
    },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: 'rgba(15, 23, 42, 0.35)',
      borderRadius: 6,
      padding: 4,
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.2)',
      marginBottom: 20,
      gap: 6,
    },
    tabButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 4,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    activeTabButton: {
      backgroundColor: 'rgba(217, 119, 6, 0.15)',
      borderWidth: 1.5,
      borderColor: '#fbbf24',
    },
    tabText: {
      color: 'rgba(255, 255, 255, 0.5)',
      fontWeight: '900',
      fontSize: 12,
      letterSpacing: 1,
    },
    activeTabText: {
      color: '#fbbf24',
    },
    errorContainer: {
      backgroundColor: 'rgba(239, 68, 68, 0.12)',
      borderWidth: 1.5,
      borderColor: '#f87171',
      borderRadius: 4,
      padding: 10,
      marginBottom: 16,
      shadowColor: '#ef4444',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    errorText: {
      color: '#f87171',
      fontSize: 12,
      textAlign: 'center',
      fontWeight: '700',
    },
    inputWrapper: {
      marginBottom: 16,
    },
    rowInputs: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    inputLabel: {
      fontSize: 10,
      fontWeight: 'bold',
      color: '#fbbf24',
      marginBottom: 6,
      letterSpacing: 1,
    },
    input: {
      backgroundColor: 'rgba(8, 10, 18, 0.7)',
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.5)',
      borderRadius: 4,
      paddingVertical: 10,
      paddingHorizontal: 12,
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '600',
    },
    phoneInputContainer: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    phonePrefix: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 12,
      backgroundColor: 'rgba(8, 10, 18, 0.7)',
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.5)',
      borderRightWidth: 0,
      borderTopLeftRadius: 4,
      borderBottomLeftRadius: 4,
    },
    phonePrefixText: {
      color: '#fbbf24',
      fontSize: 14,
      fontWeight: 'bold',
    },
    phoneInput: {
      flex: 1,
      backgroundColor: 'rgba(8, 10, 18, 0.7)',
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.5)',
      borderLeftWidth: 0,
      borderTopRightRadius: 4,
      borderBottomRightRadius: 4,
      paddingVertical: 10,
      paddingHorizontal: 12,
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '600',
    },
    submitButton: {
      backgroundColor: '#991b1b',
      borderRadius: 4,
      borderWidth: 2,
      borderColor: '#ef4444',
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 10,
      shadowColor: '#ef4444',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 5,
    },
    submitButtonText: {
      color: '#ffffff',
      fontWeight: '900',
      fontSize: 14,
      letterSpacing: 1.5,
    },
    socialContainer: {
      marginTop: 20,
      alignItems: 'center',
    },
    socialDividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    socialLine: {
      flex: 1,
      height: 1,
      backgroundColor: 'rgba(251, 191, 36, 0.25)',
    },
    socialDividerText: {
      fontSize: 9,
      color: 'rgba(255, 255, 255, 0.45)',
      fontWeight: '900',
      marginHorizontal: 8,
      letterSpacing: 1,
    },
    socialButtonsRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 20,
    },
    socialButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: 'rgba(217, 119, 6, 0.5)',
      backgroundColor: 'rgba(8, 10, 18, 0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#fbbf24',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 3,
    },
    footerText: {
      textAlign: 'center',
      fontSize: 9,
      color: '#64748B',
      marginTop: 24,
      letterSpacing: 1,
    },
  });
};
