import { StyleSheet } from 'react-native';

export const createStyles = (insets: any, width: number, height: number) => {
  const isTablet = width >= 768;
  
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#020617',
      justifyContent: 'center',
      alignItems: 'center',
    },
    background: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    video: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    overlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(2, 6, 23, 0.75)',
    },
    header: {
      alignItems: 'center',
      marginBottom: isTablet ? 24 : 12,
      zIndex: 10,
      width: '100%',
    },
    stepTitle: {
      color: '#fbbf24',
      fontSize: isTablet ? 22 : 16,
      fontWeight: 'bold',
      letterSpacing: 2,
    },
    stepIndicator: {
      color: '#F8FAFC',
      fontSize: isTablet ? 14 : 11,
      fontWeight: '600',
      marginTop: 4,
      letterSpacing: 1,
    },
    stepperContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      width: '80%',
      maxWidth: 280,
    },
    stepCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    activeStepCircle: {
      backgroundColor: 'rgba(251, 191, 36, 0.15)',
      borderColor: '#fbbf24',
    },
    currentStepCircle: {
      backgroundColor: '#fbbf24',
      borderColor: '#fbbf24',
    },
    stepCircleText: {
      color: '#64748B',
      fontSize: 11,
      fontWeight: 'bold',
    },
    activeStepCircleText: {
      color: '#fbbf24',
    },
    currentStepCircleText: {
      color: '#020617',
    },
    stepLine: {
      flex: 1,
      height: 2,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      marginHorizontal: 4,
    },
    activeStepLine: {
      backgroundColor: '#fbbf24',
    },
    card: {
      width: isTablet ? '80%' : '92%',
      maxWidth: 480,
      flex: 1,
      maxHeight: height > 700 ? '82%' : '90%', // Slightly taller card for symmetrical layout
      backgroundColor: 'rgba(15, 23, 42, 0.94)',
      borderRadius: 20,
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.08)', // Harmonious, less bright border
      padding: isTablet ? 24 : 18,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 15,
      elevation: 8,
      zIndex: 10,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    errorText: {
      color: '#ef4444',
      fontSize: 11,
      textAlign: 'center',
      fontWeight: '600',
      marginBottom: 8,
    },
    stepContent: {
      flex: 1,
    },
    stepScrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingBottom: 10,
    },
    sectionTitle: {
      fontSize: isTablet ? 24 : 18, // Larger title
      fontWeight: '800',
      color: '#F8FAFC',
      textAlign: 'center', // Symmetrical alignment
      marginTop: isTablet ? 24 : 18, // Spacer for subsequent titles
      marginBottom: 6,
    },
    sectionSubtitle: {
      fontSize: isTablet ? 13 : 11,
      color: '#94A3B8',
      textAlign: 'center', // Symmetrical alignment
      marginBottom: isTablet ? 18 : 12,
      lineHeight: 15,
    },
    genderContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: isTablet ? 20 : 14,
    },
    genderCard: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.55)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.06)',
      borderRadius: 18,
      paddingVertical: isTablet ? 20 : 14,
      paddingHorizontal: 8,
      alignItems: 'center',
      marginHorizontal: 5,
      overflow: 'hidden',
      position: 'relative',
    },
    activeGenderCard: {
      borderColor: '#fbbf24',
      borderWidth: 2,
    },
    genderAvatarWrapper: {
      width: isTablet ? 110 : 92,
      height: isTablet ? 110 : 92,
      borderRadius: isTablet ? 55 : 46,
      backgroundColor: 'rgba(8, 12, 28, 0.7)',
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      overflow: 'hidden',
    },
    activeGenderAvatarWrapper: {
      borderColor: 'rgba(255, 255, 255, 0.18)',
    },
    genderIcon: {
      fontSize: 32,
      marginBottom: 8,
    },
    genderLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: '#CBD5E1',
    },
    genderLabelMain: {
      fontSize: isTablet ? 15 : 13,
      fontWeight: '800',
      color: '#94A3B8',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
    },
    activeGenderText: {
      color: '#ffffff',
      fontWeight: '900',
    },
    ageControl: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
    },
    ageButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(245, 158, 11, 0.15)',
      borderWidth: 1.5,
      borderColor: '#f59e0b',
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 20,
    },
    ageButtonText: {
      color: '#fbbf24',
      fontSize: 20,
      fontWeight: 'bold',
    },
    ageValue: {
      fontSize: isTablet ? 24 : 20,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    label: {
      fontSize: 12,
      fontWeight: 'bold',
      color: '#fbbf24',
      marginBottom: 6,
    },
    provinceScroll: {
      flex: 1,
      marginBottom: 10,
    },
    districtScroll: {
      flex: 1,
      marginBottom: 10,
    },
    backToProvinceButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(251, 191, 36, 0.08)',
      borderWidth: 1.2,
      borderColor: 'rgba(251, 191, 36, 0.3)',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginBottom: 14,
      marginTop: 4,
    },
    backToProvinceText: {
      color: '#fbbf24',
      fontSize: 13,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    listItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      backgroundColor: 'rgba(30, 41, 59, 0.35)',
      borderRadius: 12,
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.04)',
      marginBottom: 8,
      marginHorizontal: 8,
    },
    activeListItem: {
      backgroundColor: 'rgba(245, 158, 11, 0.12)',
      borderColor: '#fbbf24',
    },
    listItemText: {
      color: '#CBD5E1',
      fontSize: 13,
      fontWeight: '700',
    },
    activeListItemText: {
      color: '#fbbf24',
    },
    listItemDesc: {
      color: '#64748B',
      fontSize: 10,
      marginTop: 4,
    },
    subListItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      backgroundColor: 'rgba(30, 41, 59, 0.35)',
      borderRadius: 12,
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.04)',
      marginBottom: 8,
      marginHorizontal: 8,
    },
    activeSubListItem: {
      backgroundColor: 'rgba(245, 158, 11, 0.15)',
      borderColor: '#fbbf24',
    },
    subListItemText: {
      color: '#CBD5E1',
      fontSize: 13,
      fontWeight: '600',
    },
    activeSubListItemText: {
      color: '#fbbf24',
    },
    backstoryScroll: {
      flex: 1,
    },
    backstoryCard: {
      backgroundColor: 'rgba(30, 41, 59, 0.35)',
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 16,
      padding: 14,
      marginBottom: 12,
      marginHorizontal: 2,
    },
    activeBackstoryCard: {
      borderColor: '#fbbf24',
      borderWidth: 1.5,
      backgroundColor: 'rgba(245, 158, 11, 0.12)',
    },
    backstoryName: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#CBD5E1',
      marginBottom: 4,
    },
    activeBackstoryText: {
      color: '#f59e0b',
    },
    backstoryDesc: {
      fontSize: 11,
      color: '#94A3B8',
      lineHeight: 15,
    },
    backstoryStats: {
      fontSize: 11,
      fontWeight: 'bold',
      color: '#10B981',
      marginTop: 6,
    },
    summaryContainer: {
      backgroundColor: 'rgba(30, 41, 59, 0.5)',
      borderRadius: 10,
      padding: 16,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255,255,255,0.05)',
    },
    summaryLabel: {
      color: '#94A3B8',
      fontSize: 13,
      fontWeight: '600',
    },
    summaryValue: {
      color: '#fbbf24',
      fontSize: 13,
      fontWeight: 'bold',
    },
    finalDisclaimer: {
      color: '#f87171',
      fontSize: 10,
      textAlign: 'center',
      marginTop: 20,
      lineHeight: 14,
      fontWeight: '600',
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 16,
      gap: 8,
      width: '100%',
    },
    backButton: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.8)',
      borderWidth: 1.5,
      borderColor: '#64748B',
      borderRadius: 8,
      paddingVertical: isTablet ? 14 : 11,
      alignItems: 'center',
    },
    backButtonText: {
      color: '#CBD5E1',
      fontWeight: 'bold',
      fontSize: 13,
    },
    nextButton: {
      flex: 2,
      backgroundColor: '#f59e0b',
      borderRadius: 8,
      paddingVertical: isTablet ? 14 : 11,
      alignItems: 'center',
    },
    nextButtonText: {
      color: '#020617',
      fontWeight: 'bold',
      fontSize: 13,
    },
    finishButton: {
      flex: 2,
      backgroundColor: '#10B981',
      borderRadius: 8,
      paddingVertical: isTablet ? 14 : 11,
      alignItems: 'center',
    },
    finishButtonText: {
      color: '#020617',
      fontWeight: 'bold',
      fontSize: 13,
    },
    genderAvatarImage: {
      width: '100%',
      height: '100%',
    },
    selectedBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#fbbf24',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: '#0f172a',
      zIndex: 20,
    },
    selectedBadgeText: {
      color: '#020617',
      fontSize: 10,
      fontWeight: 'bold',
    },
    ideologyValue: {
      fontSize: isTablet ? 15 : 13,
      fontWeight: 'bold',
      color: '#ffffff',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    genderSubLabelMain: {
      fontSize: 8,
      color: '#64748b',
      marginTop: 3,
      fontWeight: '600',
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    statRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 4,
    },
    statLabel: {
      width: 110,
      fontSize: 10,
      color: '#94a3b8',
      fontWeight: '700',
    },
    statBarBg: {
      flex: 1,
      height: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 3,
      overflow: 'hidden',
      marginHorizontal: 10,
    },
    statBarFill: {
      height: '100%',
      borderRadius: 3,
    },
    statValue: {
      width: 22,
      fontSize: 10,
      fontWeight: 'bold',
      textAlign: 'right',
    },
    ageSelectorContainer: {
      marginTop: 6,
    },
    ageConsolePanel: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: 'rgba(8, 10, 18, 0.6)',
      borderWidth: 1.2,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 12,
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginBottom: 10,
    },
    ageControlBtn: {
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.08)',
    },
    ageControlBtnText: {
      color: '#fbbf24',
      fontSize: 13,
      fontWeight: 'bold',
    },
    ageDisplayContainer: {
      alignItems: 'center',
      flex: 1,
    },
    ageValueLabel: {
      fontSize: 8,
      color: '#94a3b8',
      fontWeight: 'bold',
      letterSpacing: 1,
      marginTop: 2,
    },
    ageDescriptionCard: {
      backgroundColor: 'rgba(15, 23, 42, 0.65)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.06)',
      borderRadius: 12,
      padding: 12,
    },
    ageDescriptionTitle: {
      fontSize: 13,
      fontWeight: 'bold',
      color: '#fbbf24',
      marginBottom: 4,
    },
    ageDescriptionText: {
      fontSize: 10,
      color: '#cbd5e1',
      lineHeight: 14,
      marginBottom: 8,
    },
    statsDivider: {
      height: 1,
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      marginBottom: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(2, 6, 23, 0.85)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '85%',
      maxWidth: 340,
      backgroundColor: 'rgba(15, 23, 42, 0.96)',
      borderWidth: 1.5,
      borderColor: '#ef4444',
      borderRadius: 18,
      padding: 24,
      alignItems: 'center',
      shadowColor: '#ef4444',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 10,
    },
    modalIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      borderWidth: 1.5,
      borderColor: '#ef4444',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalIconText: {
      fontSize: 28,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#ef4444',
      letterSpacing: 2,
      marginBottom: 10,
      textTransform: 'uppercase',
    },
    modalMessage: {
      fontSize: 13,
      color: '#cbd5e1',
      textAlign: 'center',
      lineHeight: 18,
      marginBottom: 20,
    },
    modalCloseBtn: {
      backgroundColor: 'rgba(239, 68, 68, 0.15)',
      borderWidth: 1.2,
      borderColor: '#ef4444',
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 28,
      width: '100%',
      alignItems: 'center',
    },
    modalCloseBtnText: {
      color: '#ffffff',
      fontWeight: 'bold',
      fontSize: 13,
      letterSpacing: 1,
    },
    // Premium T.C. Citizenship ID Card Styles
    idCard: {
      backgroundColor: '#0a1424',
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: 'rgba(45, 212, 191, 0.25)',
      padding: 12,
      marginVertical: 10,
      position: 'relative',
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    idCardHologram: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    idCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(45, 212, 191, 0.2)',
      paddingBottom: 6,
      marginBottom: 8,
    },
    idCardHeaderTitle: {
      color: '#ffffff',
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
    },
    idCardHeaderSubtitle: {
      color: '#64748b',
      fontSize: 6,
      fontWeight: '700',
      letterSpacing: 0.5,
      marginTop: 1,
    },
    idCardChip: {
      width: 22,
      height: 18,
      borderRadius: 3,
      backgroundColor: '#fbbf24',
      borderWidth: 1,
      borderColor: '#d97706',
      paddingVertical: 1,
      paddingHorizontal: 2,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    idCardChipLine: {
      height: 1,
      width: '100%',
      backgroundColor: '#9a3412',
      marginVertical: 1.5,
    },
    idCardChipInner: {
      position: 'absolute',
      width: 10,
      height: 10,
      backgroundColor: '#fbbf24',
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: '#d97706',
    },
    idCardBody: {
      flexDirection: 'row',
      gap: 10,
    },
    idCardLeftCol: {
      width: 76,
      alignItems: 'center',
    },
    idCardPhotoFrame: {
      width: 72,
      height: 86,
      borderRadius: 6,
      backgroundColor: 'rgba(15, 23, 42, 0.85)',
      borderWidth: 1.2,
      borderColor: 'rgba(45, 212, 191, 0.4)',
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
    },
    idCardSerial: {
      color: '#ef4444',
      fontSize: 7,
      fontWeight: 'bold',
      marginTop: 4,
      letterSpacing: 0.5,
    },
    idCardRightCol: {
      flex: 1,
      gap: 4,
    },
    idCardRow: {
      flexDirection: 'row',
      borderBottomWidth: 0.5,
      borderBottomColor: 'rgba(255, 255, 255, 0.05)',
      paddingBottom: 2,
    },
    idCardFieldLabel: {
      color: '#2dd4bf',
      fontSize: 6,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    idCardFieldValue: {
      color: '#cbd5e1',
      fontSize: 9,
      fontWeight: '700',
      marginTop: 0.5,
    },
    // Pedestal stand styles
    pedestalContainer: {
      alignItems: 'center',
      marginTop: 14,
      marginBottom: 10,
    },
    pedestalTitle: {
      color: '#94a3b8',
      fontSize: 10,
      fontWeight: 'bold',
      letterSpacing: 1.2,
      marginBottom: 6,
    },
    hologramBase: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 180,
      height: 120,
      position: 'relative',
    },
    hologramRingBg: {
      position: 'absolute',
      bottom: 6,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    fullCharacterWrapper: {
      width: 90,
      height: 110,
      justifyContent: 'center',
      alignItems: 'center',
      transform: [{ translateY: -10 }],
    },
    // Details styles
    detailsRowContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginVertical: 10,
      gap: 12,
      width: '100%',
    },
    detailCapsuleIdeology: {
      flex: 1,
      backgroundColor: '#0a1424',
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#10b981',
      paddingVertical: 14,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 4,
    },
    detailCapsuleRecord: {
      flex: 1,
      backgroundColor: '#0a1424',
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: '#10b981',
      paddingVertical: 14,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 4,
    },
    detailCapsuleLabel: {
      color: '#64748b',
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 6,
      backgroundColor: 'transparent',
    },
    detailCapsuleValue: {
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
      backgroundColor: 'transparent',
    },
  });
};
